// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SendEmalWebApi.Data;

#nullable disable

namespace SendEmalWebApi.Migrations
{
    [DbContext(typeof(SenderContext))]
    partial class SenderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SendEmalWebApi.Model.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LogId");

                    b.ToTable("Emails", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "test1@mail.ru",
                            LogId = 1
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "test2@gmail.com",
                            LogId = 1
                        });
                });

            modelBuilder.Entity("SendEmalWebApi.Model.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieledMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Hello my friends",
                            CreatedDate = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            FieledMessage = "",
                            Result = "OK",
                            Subject = "My first email"
                        });
                });

            modelBuilder.Entity("SendEmalWebApi.Model.Email", b =>
                {
                    b.HasOne("SendEmalWebApi.Model.Log", "Log")
                        .WithMany("Recipient")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");
                });

            modelBuilder.Entity("SendEmalWebApi.Model.Log", b =>
                {
                    b.Navigation("Recipient");
                });
#pragma warning restore 612, 618
        }
    }
}
